openapi: 3.0.1
info:
  title: Standard APIs
  description: ''
  version: 1.0.0
tags: []
paths:
  https://bidf.fiingroup.vn/api/v1/Standard/SearchCompany:
    get:
      summary: SearchCompany
      deprecated: false
      description: Search company by indicator
      tags: []
      parameters:
        - name: IsinCode
          in: query
          description: ''
          required: false
          example: ''
          schema:
            type: string
        - name: OrganizationName
          in: query
          description: ''
          required: false
          example: ''
          schema:
            type: string
        - name: TaxCode
          in: query
          description: ''
          required: false
          example: ''
          schema:
            type: string
        - name: Ticker
          in: query
          description: ''
          required: false
          example: ''
          schema:
            type: string
        - name: EnterpriseCode
          in: query
          description: ''
          required: false
          example: ''
          schema:
            type: string
        - name: Page
          in: query
          description: ''
          required: false
          example: ''
          schema:
            type: integer
        - name: PageSize
          in: query
          description: ''
          required: false
          example: ''
          schema:
            type: integer
        - name: Accept
          in: header
          description: ''
          required: true
          example: application/octet-stream
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
      security:
        - bearer: []
