openapi: 3.0.1
info:
  title: Standard APIs
servers:
  - url: https://bidf.fiingroup.vn/api/v1/Standard/SearchCompany
paths:
  https://bidf.fiingroup.vn/api/v1/Standard/SearchCompany:
    get:
      summary: SearchCompany
      deprecated: false
      description: Search company by indicator
       ### Search Company Input Indicators

        | Field Name     | Type    | Description                                  |
        |----------------|---------|----------------------------------------------|
        | IsinCode       | string  | International Securities Identification ...  |
        | OrganizationName | string| Full name of the company                     |
        | TaxCode        | string  | Company tax code                             |
        | Ticker         | string  | Stock code                                   |
        | Page           | integer | Page number (default 1)                      |
        | PageSize       | integer | Records per page (default 100)               |
      
      parameters:
        - name: IsinCode
          in: query
          description: ''
          required: false
          schema:
            type: string
        - name: OrganizationName
          in: query
          required: false
          schema:
            type: string
        - name: TaxCode
          in: query
          required: false
          schema:
            type: string
        - name: Ticker
          in: query
          required: false
          schema:
            type: string
        - name: EnterpriseCode
          in: query
          required: false
          schema:
            type: string
        - name: Page
          in: query
          required: false
          schema:
            type: integer
        - name: PageSize
          in: query
          required: false
          schema:
            type: integer

    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object

      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
      security:
        - bearer: []
