openapi: 3.0.1
info:
  title: Standard APIs

paths:
  https://bidf.fiingroup.vn/api/v1/Standard/SearchCompany:
    get:
      summary: SearchCompany
      deprecated: false
      description: Search company by indicator
      
      parameters:
        - name: IsinCode
          in: query
          description: ''
          required: false
          schema:
            type: string
        - name: OrganizationName
          in: query
          required: false
          schema:
            type: string
        - name: TaxCode
          in: query
          required: false
          schema:
            type: string
        - name: Ticker
          in: query
          required: false
          schema:
            type: string
        - name: EnterpriseCode
          in: query
          required: false
          schema:
            type: string
        - name: Page
          in: query
          required: false
          schema:
            type: integer
        - name: PageSize
          in: query
          required: false
          schema:
            type: integer

    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object

      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
      security:
        - bearer: []
